Name:           ros-hydro-moveit-python
Version:        0.2.7
Release:        0%{?dist}
Summary:        ROS moveit_python package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/moveit_python
Source0:        %{name}-%{version}.tar.gz

Requires:       assimp-python
Requires:       ros-hydro-actionlib
Requires:       ros-hydro-geometry-msgs
Requires:       ros-hydro-moveit-msgs
Requires:       ros-hydro-rospy
Requires:       ros-hydro-shape-msgs
Requires:       ros-hydro-tf
BuildRequires:  ros-hydro-catkin

%description
A pure-python interaface to the MoveIt! ROS API.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Wed Nov 19 2014 Michael Ferguson <fergs@unboundedrobotics.com> - 0.2.7-0
- Autogenerated by Bloom

* Sun Nov 16 2014 Michael Ferguson <fergs@unboundedrobotics.com> - 0.2.6-0
- Autogenerated by Bloom

